# Name of the container image (use your-user/app-name on external registries).
image: hokyunrhee/kamal-ssm-deploy

x-instance-id: &instance-id i-xxxxxxxxxxxxxxxxx

# Global setting for all hooks.
hooks_output: :verbose

# Deploy to these servers.
servers:
  web:
    - *instance-id
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Where you keep your container images.
registry:
  # Alternatives: hub.docker.com / registry.digitalocean.com / ghcr.io / ...
  server: localhost:5555

  # Needed for authenticated registries.
  # username: your-user

  # Always use an access token rather than real password when possible.
  # password:
  #   - KAMAL_REGISTRY_PASSWORD
